"""'Uploading'

Revision ID: 314bf30dc312
Revises: 7e85f5d8e8e5
Create Date: 2020-12-08 21:02:12.769208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314bf30dc312'
down_revision = '7e85f5d8e8e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exstudents', sa.Column('extra1', sa.Text(), nullable=True))
    op.add_column('exstudents', sa.Column('extra2', sa.Text(), nullable=True))
    op.add_column('exstudents', sa.Column('extra3', sa.Text(), nullable=True))
    op.add_column('prospects', sa.Column('extra1', sa.Text(), nullable=True))
    op.add_column('prospects', sa.Column('extra2', sa.Text(), nullable=True))
    op.add_column('prospects', sa.Column('extra3', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('extra1', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('extra2', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('extra3', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'extra3')
    op.drop_column('students', 'extra2')
    op.drop_column('students', 'extra1')
    op.drop_column('prospects', 'extra3')
    op.drop_column('prospects', 'extra2')
    op.drop_column('prospects', 'extra1')
    op.drop_column('exstudents', 'extra3')
    op.drop_column('exstudents', 'extra2')
    op.drop_column('exstudents', 'extra1')
    # ### end Alembic commands ###
