"""'Uploading'

Revision ID: 3987fe177d8f
Revises: 314bf30dc312
Create Date: 2020-12-08 21:42:27.312831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3987fe177d8f'
down_revision = '314bf30dc312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('company_name', sa.String(), nullable=True))
    op.add_column('prospects', sa.Column('data_source', sa.String(), nullable=True))
    op.add_column('students', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'dob')
    op.drop_column('prospects', 'data_source')
    op.drop_column('prospects', 'company_name')
    # ### end Alembic commands ###
