"""'Floating'

Revision ID: 435979a76c56
Revises: 8b2b7802573c
Create Date: 2020-12-30 17:28:12.400208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435979a76c56'
down_revision = '8b2b7802573c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('theme', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'theme')
    # ### end Alembic commands ###
