"""'Initial'

Revision ID: 6ec48b62d4e2
Revises: 92b4fae90168
Create Date: 2020-12-31 13:27:28.028264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec48b62d4e2'
down_revision = '92b4fae90168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
