"""'Initial'

Revision ID: 92b4fae90168
Revises: 
Create Date: 2020-12-31 13:25:23.179347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b4fae90168'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exstudents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('courses', sa.Text(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('referral_name', sa.String(), nullable=True),
    sa.Column('referral_number', sa.String(), nullable=True),
    sa.Column('referral_email', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('extra1', sa.Text(), nullable=True),
    sa.Column('extra2', sa.Text(), nullable=True),
    sa.Column('extra3', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('courses', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('extra1', sa.Text(), nullable=True),
    sa.Column('extra2', sa.Text(), nullable=True),
    sa.Column('extra3', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('courses', sa.Text(), nullable=True),
    sa.Column('registration_fee', sa.Float(), nullable=True),
    sa.Column('tutorial_fee', sa.Float(), nullable=True),
    sa.Column('course_fee', sa.Float(), nullable=True),
    sa.Column('payment_1', sa.Float(), nullable=True),
    sa.Column('payment_2', sa.Float(), nullable=True),
    sa.Column('payment_3', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('exam', sa.String(), nullable=True),
    sa.Column('remark_1', sa.Text(), nullable=True),
    sa.Column('remark_2', sa.Text(), nullable=True),
    sa.Column('extra1', sa.Text(), nullable=True),
    sa.Column('extra2', sa.Text(), nullable=True),
    sa.Column('extra3', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('lesson')
    op.drop_table('user')
    op.drop_table('students')
    op.drop_table('prospects')
    op.drop_table('exstudents')
    op.drop_table('courses')
    # ### end Alembic commands ###
