"""'addedfeatues'

Revision ID: e48ac42119e6
Revises: 3987fe177d8f
Create Date: 2020-12-14 02:34:34.807313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e48ac42119e6'
down_revision = '3987fe177d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prospects', sa.Column('courses', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'courses')
    # ### end Alembic commands ###
